import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { SITE_NAME } from "@/constants/seo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: SITE_NAME,
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="bg-body main-container">
					<StoreProvider>{children}</StoreProvider>
				</main>
			</body>
		</html>
	);
}
